"""add salt field to APIKey model

Revision ID: 5a4ef8ee2a4c
Revises: d4e248681d6a
Create Date: 2026-01-07 18:44:16.573638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5a4ef8ee2a4c'
down_revision: Union[str, Sequence[str], None] = 'd4e248681d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikey', 'salt')
    # ### end Alembic commands ###
