"""fix types on FKs

Revision ID: 5cd2abc67a43
Revises: 8503371000b4
Create Date: 2026-01-07 16:40:30.386966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5cd2abc67a43'
down_revision: Union[str, Sequence[str], None] = '8503371000b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('apikey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_hashed_key'), 'apikey', ['hashed_key'], unique=False)
    op.create_index(op.f('ix_apikey_user'), 'apikey', ['user'], unique=False)
    op.create_table('capsule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('time_held', sa.Interval(), nullable=False),
    sa.Column('replying_to', sa.Uuid(), nullable=True),
    sa.Column('reply_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['replying_to'], ['capsule.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capsule_user'), 'capsule', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_user'), table_name='capsule')
    op.drop_table('capsule')
    op.drop_index(op.f('ix_apikey_user'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_hashed_key'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
