"""add prefix to APIKey model

Revision ID: 69c9ea8c55f5
Revises: 7940895eabc6
Create Date: 2026-01-07 22:09:04.311050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '69c9ea8c55f5'
down_revision: Union[str, Sequence[str], None] = '7940895eabc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False))
    op.create_index(op.f('ix_apikey_prefix'), 'apikey', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_prefix'), table_name='apikey')
    op.drop_column('apikey', 'prefix')
    # ### end Alembic commands ###
