"""fix capsule self reference

Revision ID: 7940895eabc6
Revises: 5a4ef8ee2a4c
Create Date: 2026-01-07 21:32:03.187376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7940895eabc6'
down_revision: Union[str, Sequence[str], None] = '5a4ef8ee2a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('replying_to_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'capsule', 'capsule', ['replying_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capsule', type_='foreignkey')
    op.drop_column('capsule', 'replying_to_id')
    # ### end Alembic commands ###
