"""remove content restriction to fit ciphertext

Revision ID: 9c10d1ce38e4
Revises: 9cb0520ae27c
Create Date: 2026-01-14 22:10:51.231310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9c10d1ce38e4'
down_revision: Union[str, Sequence[str], None] = '9cb0520ae27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
