"""refactor to dynamic reply check

Revision ID: 9cb0520ae27c
Revises: a4464c90188e
Create Date: 2026-01-14 18:24:27.180404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9cb0520ae27c'
down_revision: Union[str, Sequence[str], None] = 'a4464c90188e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'reply_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('reply_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
