"""add conversation model

Revision ID: a4464c90188e
Revises: a8e906b50dae
Create Date: 2026-01-14 17:50:40.386604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a4464c90188e'
down_revision: Union[str, Sequence[str], None] = 'a8e906b50dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('latest_capsule_id', sa.Uuid(), nullable=True),
    sa.Column('reply_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['latest_capsule_id'], ['capsule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.add_column('capsule', sa.Column('conversation_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_capsule_is_conversation_head'), table_name='capsule')
    op.create_index(op.f('ix_capsule_conversation_id'), 'capsule', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'capsule', 'conversation', ['conversation_id'], ['id'])
    op.drop_column('capsule', 'is_conversation_head')
    op.drop_column('capsule', 'reply_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('reply_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('capsule', sa.Column('is_conversation_head', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'capsule', type_='foreignkey')
    op.drop_index(op.f('ix_capsule_conversation_id'), table_name='capsule')
    op.create_index(op.f('ix_capsule_is_conversation_head'), 'capsule', ['is_conversation_head'], unique=False)
    op.drop_column('capsule', 'conversation_id')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
