"""add conversation verifier

Revision ID: a8e906b50dae
Revises: a4b5454beda2
Create Date: 2026-01-14 16:58:25.213861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a8e906b50dae'
down_revision: Union[str, Sequence[str], None] = 'a4b5454beda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('is_conversation_head', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_capsule_is_conversation_head'), 'capsule', ['is_conversation_head'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_is_conversation_head'), table_name='capsule')
    op.drop_column('capsule', 'is_conversation_head')
    # ### end Alembic commands ###
