"""add creation date to verification model and sent bool

Revision ID: b3f839c3cc9e
Revises: f1e1c2c956e4
Create Date: 2026-01-18 19:56:18.670723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b3f839c3cc9e'
down_revision: Union[str, Sequence[str], None] = 'f1e1c2c956e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('sent', sa.Boolean(), nullable=False))
    op.add_column('verification', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification', 'creation_date')
    op.drop_column('capsule', 'sent')
    # ### end Alembic commands ###
