"""add relationships to models

Revision ID: d4e248681d6a
Revises: 5cd2abc67a43
Create Date: 2026-01-07 16:55:21.753013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd4e248681d6a'
down_revision: Union[str, Sequence[str], None] = '5cd2abc67a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_apikey_user'), table_name='apikey')
    op.create_index(op.f('ix_apikey_user_id'), 'apikey', ['user_id'], unique=False)
    op.drop_constraint(op.f('apikey_user_fkey'), 'apikey', type_='foreignkey')
    op.create_foreign_key(None, 'apikey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('apikey', 'user')
    op.add_column('capsule', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_capsule_user'), table_name='capsule')
    op.create_index(op.f('ix_capsule_user_id'), 'capsule', ['user_id'], unique=False)
    op.drop_constraint(op.f('capsule_user_fkey'), 'capsule', type_='foreignkey')
    op.drop_constraint(op.f('capsule_replying_to_fkey'), 'capsule', type_='foreignkey')
    op.create_foreign_key(None, 'capsule', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('capsule', 'replying_to')
    op.drop_column('capsule', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('capsule', sa.Column('replying_to', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'capsule', type_='foreignkey')
    op.create_foreign_key(op.f('capsule_replying_to_fkey'), 'capsule', 'capsule', ['replying_to'], ['id'])
    op.create_foreign_key(op.f('capsule_user_fkey'), 'capsule', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_capsule_user_id'), table_name='capsule')
    op.create_index(op.f('ix_capsule_user'), 'capsule', ['user'], unique=False)
    op.drop_column('capsule', 'user_id')
    op.add_column('apikey', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.create_foreign_key(op.f('apikey_user_fkey'), 'apikey', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_apikey_user_id'), table_name='apikey')
    op.create_index(op.f('ix_apikey_user'), 'apikey', ['user'], unique=False)
    op.drop_column('apikey', 'user_id')
    # ### end Alembic commands ###
