"""add email verification model

Revision ID: f1e1c2c956e4
Revises: 9c10d1ce38e4
Create Date: 2026-01-18 19:23:12.255641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e1c2c956e4'
down_revision: Union[str, Sequence[str], None] = '9c10d1ce38e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_user_id'), 'verification', ['user_id'], unique=False)
    op.alter_column('conversation', 'latest_capsule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'email_verified')
    op.alter_column('conversation', 'latest_capsule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_verification_user_id'), table_name='verification')
    op.drop_table('verification')
    # ### end Alembic commands ###
