# Generated by Django 5.2.6 on 2025-09-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalAPI.capsule'),
        ),
    ]
