# Generated by Django 5.2.6 on 2025-09-07 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0003_draft_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 7, 17, 28, 4, 958383, tzinfo=datetime.timezone.utc)),
        ),
    ]
