# Generated by Django 5.2.6 on 2025-09-07 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0004_capsule_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 7, 17, 29, 26, 265312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
