# Generated by Django 5.2.6 on 2025-09-07 17:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0005_alter_capsule_release_date_delete_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 7, 17, 31, 12, 492541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('draft_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField()),
                ('locked_time', models.DurationField()),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalAPI.capsule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
