# Generated by Django 5.2.6 on 2025-09-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0006_alter_capsule_release_date_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Capsule',
        ),
    ]
