# Generated by Django 5.2.6 on 2025-09-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalAPI', '0008_capsule_draft_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='message',
            new_name='encrypted_message',
        ),
    ]
